### ISSUE TITLE
Module not working with latest Ti SDK i.e 5.2.0

### ISSUE THREAD

**Issue by speedyankur** [freshheads/fh.imagefactory#4]
Please recompile and upload new release working with Ti SDk 5.2.0 and Android 6.0

**Comment by m1ga** [comment]
does it work when you use the new permissions on anroid 6? E.g. got to your app-info and check the storage permission or use this module: https://github.com/gimdongwoo/Ti-Android-RequestStoragePermission and put the fh.imagefactory module in the true condition. Perhaps you could use that as a workaround for now

**Comment by freedevcom** [comment]
I have the same problem: I can't compile my project with titanium sdks 5.2.0 and android 6.0 using fh.imagefactory: here it is the open issue on jira https://jira.appcelerator.org/browse/AC-3512. I can't understand why the module  https://github.com/gimdongwoo/Ti-Android-RequestStoragePermission is involved, since we are still in building phase.

**Comment by annakozy2011** [comment]
I am just a random passerby, but SDK 5.2.0 has a bug on android 6.0, it cant store any file without external storage permission (not even those on internal storage). Please compile with 5.0.2 or some release candidate for 5.3.x

**Comment by Lenndev** [comment]
Using this plugin with Ti SDK 5.5.1 on android 6.0, storage permissions are set, but the rotation isn't working... any solutions yet?

**Comment by m1ga** [comment]
@Lenndev any error message? The rotation only works if there are correct EXIF information. Inside your console log you should see something like `Detected orientation:`

**Comment by Geek-Fish** [comment]
Mine still works fine in all 5.X.XGA's with Android 6. I suspect you aren't getting EXIF data as @m1ga said. I was trying to rotate thumbnails originally and those do not have EXIF data on Android, so i had to rebuild a thumbnail and use the original EXIF data from the original image to rotate.

**Comment by m1ga** [comment]
closing this since we are at SDK 7 already
