### ISSUE TITLE
Still broken for ti sdk 7.0

### ISSUE THREAD

**Issue by btknorr** [freshheads/fh.imagefactory#8]
This is the error you get opening your app when using the new version 3.0

[ERROR] TiApplication: (main) [20,2049] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt3__112__next_primeEm" referenced by "/data/app/com.starterstep.broadcast-2/lib/arm64/libfh.imagefactory.so"...; Titanium 7.0.0,2017/12/05 13:30,undefined
[ERROR] TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt3__112__next_primeEm" referenced by "/data/app/com.starterstep.broadcast-2/lib/arm64/libfh.imagefactory.so"...
[ERROR] TiApplication: 	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
[ERROR] TiApplication: 	at java.lang.System.loadLibrary(System.java:1530)
[ERROR] TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
[ERROR] TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
[ERROR] TiApplication: 	at com.starterstep.broadcast.ProjectBroadcastApplication.onCreate(ProjectBroadcastApplication.java:55)
[ERROR] TiApplication: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
[ERROR] TiApplication: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5881)
[ERROR] TiApplication: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
[ERROR] TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718)
[ERROR] TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] TiApplication: 	at android.os.Looper.loop(Looper.java:154)
[ERROR] TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:6688)
[ERROR] TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by m1ga** [comment]
I think there was a bug using the auto-update. When I recompile the module it works without an error. Please try 3.0.1: https://github.com/freshheads/fh.imagefactory/blob/master/android/dist/fh.imagefactory-android-3.0.1.zip

**Comment by btknorr** [comment]
This version works great...thanks for the quick response!
